version: 0.2

phases:
  build:
    commands:
      - echo "Creating folder on local machine"
      - mkdir "C:\Users\SSS2022259\pipeline"
      # Add any other build commands you need

artifacts:
  files: '**/*'
